Notes March 17th:

bullous_impetigo: '12318008'

non_bullous_impetigo: '238374001'

urinary_catheter_passport_given: '1064621000000108'

uti: '10812041000119103'

check inclusion/exclusion criteria - patient id 1, 7, 10, 11

# Check output

In [1]:
import pandas as pd

In [20]:
# data = pd.read_csv("../output/dataset_patients.csv.gz")
# data = pd.read_csv("../output/dataset_patients_debug.csv.gz")
data = pd.read_csv("../output/dataset_patients_2024-02-01.csv.gz")
# data = pd.read_csv("../output/dataset_patients_2024-03-01.csv.gz")
# data = pd.read_csv("../output/dataset_patients_combined.csv.gz")


data.head(3)

,patient_id,start_date,index_date,registered_start,registered_index,alive,sex,age,date_of_birth,imd,...,has_ae_insectbite_non_primary,ae_otitismedia_primary_count,has_ae_otitismedia_non_primary,ae_sorethroat_primary_count,has_ae_sorethroat_non_primary,ae_shingles_primary_count,has_ae_shingles_non_primary,ae_impetigo_primary_count,has_ae_impetigo_non_primary,appointment_count
0,1,2024-02-01,2024-02-29,T,T,T,unknown,91,1932-07-01,Missing,...,F,0,F,0,F,0,F,0,F,0
1,2,2024-02-01,2024-02-29,T,T,T,female,95,1928-06-01,Missing,...,F,0,F,0,F,0,F,0,F,0
2,3,2024-02-01,2024-02-29,T,T,T,male,62,1961-07-01,Missing,...,F,0,F,0,F,0,F,0,F,0

In [21]:
data['start_date'] = pd.to_datetime(data['start_date'])
data.value_counts('start_date')

start_date
2024-02-01    500
Name: count, dtype: int64

In [22]:
data['practice'].nunique()

390

In [23]:
data.groupby('start_date')['practice'].nunique()

start_date
2024-02-01    390
Name: practice, dtype: int64

In [24]:
data.columns

Index(['patient_id', 'start_date', 'index_date', 'registered_start',
       'registered_index', 'alive', 'sex', 'age', 'date_of_birth', 'imd',
       'ethnicity', 'practice', 'stp', 'region', 'pf_consultation_general',
       'numerator_pf_event_uti', 'numerator_pf_consultation_uti',
       'numerator_pf_episode_uti', 'numerator_pf_event_sinusitis',
       'numerator_pf_consultation_sinusitis', 'numerator_pf_episode_sinusitis',
       'numerator_pf_event_insectbite', 'numerator_pf_consultation_insectbite',
       'numerator_pf_episode_insectbite', 'numerator_pf_event_otitismedia',
       'numerator_pf_consultation_otitismedia',
       'numerator_pf_episode_otitismedia', 'numerator_pf_event_sorethroat',
       'numerator_pf_consultation_sorethroat',
       'numerator_pf_episode_sorethroat', 'numerator_pf_event_shingles',
       'numerator_pf_consultation_shingles', 'numerator_pf_episode_shingles',
       'numerator_pf_event_impetigo', 'numerator_pf_consultation_impetigo',
       'numerator_pf_episode_impetigo',
       'pf_consultation_general_butno_condition', 'numerator_gp_event_uti',
       'numerator_gp_consultation_uti', 'numerator_gp_episode_uti',
       'numerator_gp_event_sinusitis', 'numerator_gp_consultation_sinusitis',
       'numerator_gp_episode_sinusitis', 'numerator_gp_event_insectbite',
       'numerator_gp_consultation_insectbite',
       'numerator_gp_episode_insectbite', 'numerator_gp_event_otitismedia',
       'numerator_gp_consultation_otitismedia',
       'numerator_gp_episode_otitismedia', 'numerator_gp_event_sorethroat',
       'numerator_gp_consultation_sorethroat',
       'numerator_gp_episode_sorethroat', 'numerator_gp_event_shingles',
       'numerator_gp_consultation_shingles', 'numerator_gp_episode_shingles',
       'numerator_gp_event_impetigo', 'numerator_gp_consultation_impetigo',
       'numerator_gp_episode_impetigo', 'pregnancy_end_recent',
       'pregnancy_end', 'pregnancy_edd', 'pregnancy_code', 'pregnant',
       'pregnant_this_month', 'bullous_impetigo_this_month',
       'recurrent_impetigo_this_year', 'catheter_status', 'recurrent_uti_6m',
       'recurrent_uti_12m', 'recurrent_uti', 'include_patient_otitis_media',
       'include_patient_sinusitis', 'include_patient_sore_throat',
       'include_patient_insect_bites', 'include_patient_shingles',
       'include_patient_impetigo', 'include_patient_uuti',
       'include_patient_overall_eligible', 'ae_attendance_count',
       'ae_uti_primary_count', 'has_ae_uti_non_primary',
       'ae_sinusitis_primary_count', 'has_ae_sinusitis_non_primary',
       'ae_insectbite_primary_count', 'has_ae_insectbite_non_primary',
       'ae_otitismedia_primary_count', 'has_ae_otitismedia_non_primary',
       'ae_sorethroat_primary_count', 'has_ae_sorethroat_non_primary',
       'ae_shingles_primary_count', 'has_ae_shingles_non_primary',
       'ae_impetigo_primary_count', 'has_ae_impetigo_non_primary',
       'appointment_count'],
      dtype='object')

In [27]:
data[data['pf_consultation_general']>0].head(10)[
    ['patient_id','start_date','pf_consultation_general','pf_consultation_general_butno_condition',
     'numerator_pf_event_sorethroat','numerator_pf_consultation_sorethroat','numerator_pf_episode_sorethroat',
     'numerator_pf_event_shingles','numerator_pf_consultation_shingles','numerator_pf_episode_shingles']]

,patient_id,start_date,pf_consultation_general,pf_consultation_general_butno_condition,numerator_pf_event_sorethroat,numerator_pf_consultation_sorethroat,numerator_pf_episode_sorethroat,numerator_pf_event_shingles,numerator_pf_consultation_shingles,numerator_pf_episode_shingles
116,118,2024-02-01,1,0,1,1,1,1,1,1
195,199,2024-02-01,2,0,2,2,2,0,0,0
412,424,2024-02-01,2,1,1,1,1,0,0,0

In [55]:
data[['patient_id','bullous_impetigo_this_month', 'recurrent_impetigo_this_year',
       'catheter_status', 'recurrent_uti_6m', 'recurrent_uti_12m',
       'recurrent_uti', 
       'include_patient_impetigo', 'include_patient_uuti',
       'include_patient_overall_eligible']].head(20)

,patient_id,bullous_impetigo_this_month,recurrent_impetigo_this_year,catheter_status,recurrent_uti_6m,recurrent_uti_12m,recurrent_uti,include_patient_impetigo,include_patient_uuti,include_patient_overall_eligible
0,1,T,F,F,F,F,F,F,F,T
1,2,F,F,F,F,F,F,T,F,T
2,3,F,F,F,F,F,F,T,F,T
3,4,F,F,F,F,F,F,T,F,T
4,5,F,F,F,F,F,F,T,F,T
5,6,F,F,F,F,F,F,T,F,T
6,7,F,T,F,F,F,F,F,T,T
7,8,F,F,F,F,F,F,T,F,T
8,9,F,F,F,F,F,F,T,F,T
9,10,F,F,F,F,T,T,T,F,T
10,11,F,F,T,F,F,F,T,F,T
11,12,F,F,F,F,F,F,T,F,T
12,13,F,F,F,F,F,F,T,F,T
13,14,F,F,F,F,F,F,T,F,T
14,15,F,F,F,F,F,F,T,F,T
15,16,F,F,F,F,F,F,T,F,T
16,17,F,F,F,F,F,F,T,F,T
17,18,F,F,F,F,F,F,T,F,T
18,19,F,F,F,F,F,F,T,F,T
19,20,F,F,F,F,F,F,T,F,T

In [11]:
data['numerator_pf_consultation_sorethroat'].sum()

0

In [12]:
data['numerator_pf_consultation_uti'].sum()

0

In [13]:
data.shape

(498, 93)

# Debug

In [1]:
import pandas as pd

In [86]:
df_events = pd.read_csv("../dummy-folder/clinical_events.csv",dtype={"consultation_id": str, "snomedct_code": str})
df_events['date'] = pd.to_datetime(df_events['date'])
# df_events['snomedct_code'] = df_events['snomedct_code'].astype(str)
df_events.head(2)

   patient_id consultation_id       date   snomedct_code
0           1             875 2009-10-06  92431000000100
1           2             816 1932-01-05       270465005

In [87]:
df_events['date'].min(), df_events['date'].max()

(Timestamp('1904-07-02 00:00:00'), Timestamp('2026-03-07 00:00:00'))

In [88]:
df_events[df_events['snomedct_code']=="2129921000000100"]

      patient_id consultation_id       date     snomedct_code
124           27            -155 1978-10-19  2129921000000100
499          118             114 2024-02-11  2129921000000100
872          199            -855 2008-03-09  2129921000000100
1358         323             552 1985-12-28  2129921000000100
1915         480              91 2017-07-20  2129921000000100

In [89]:
start_date = '2023-01-01'
index_date = '2025-03-01'
data = df_events[(start_date<=df_events['date'])&(df_events['date']<index_date)]
data.shape

(180, 4)

In [90]:
data

      patient_id consultation_id       date    snomedct_code
12             5            -262 2023-07-30         49202008
13             5             -86 2024-08-11  977791000000109
17             5             559 2023-01-23  107691000000105
19             5             799 2024-09-08        315634007
25             5             989 2024-02-14   92631000000103
...          ...             ...        ...              ...
1997         504            -176 2023-02-18   92391000000108
2017         505             940 2023-06-27         17095009
2019         505             996 2024-08-21  977381000000106
2028         510             698 2025-02-02         83584002
2031         511              32 2023-07-09         25804004

[180 rows x 4 columns]

In [91]:
pf_consultation_cp_minorillness = ["1577041000000109"]
pf_consultation_service = ["983341000000102"]
pf_consultation_cp_service = ["2129921000000100"]
pf_consultation_services_combined = pf_consultation_cp_minorillness + pf_consultation_service + pf_consultation_cp_service
pf_consultation_services_combined

['1577041000000109', '983341000000102', '2129921000000100']

In [92]:
data[data['snomedct_code'].isin(pf_consultation_services_combined)]

     patient_id consultation_id       date     snomedct_code
229          47             542 2024-05-21  1577041000000109
499         118             114 2024-02-11  2129921000000100

In [93]:
pf_id = '114'
selected_pf_id_events = df_events[df_events['consultation_id']==pf_id]
selected_pf_id_events

     patient_id consultation_id       date     snomedct_code
499         118             114 2024-02-11  2129921000000100
500         118             114 2024-02-11         363746003

In [55]:
uti_code = ["1090711000000102"]
sinusitis_code = ["15805002"]
insectbite_code = ["262550002"]
otitismedia_code = ["3110003"]
sorethroat_code = ["363746003"]
shingles_code = ["4740000"]
impetigo_code = ["48277006"]

# Check practice level data

In [66]:
data = pd.read_csv("../output/practice_measures.csv")
data.head(3)

,measure,interval_start,interval_end,ratio,numerator,denominator,practice,stp,region,start_date
0,population,2024-02-01,2024-02-29,1.0,1,1,681,E54000002,London,2024-02-01
1,appointments_total,2024-02-01,2024-02-29,0.0,0,1,681,E54000002,London,2024-02-01
2,pf_uti,2024-02-01,2024-02-29,0.0,0,1,681,E54000002,London,2024-02-01

In [67]:
data.groupby('interval_start')['practice'].nunique()

interval_start
2024-02-01    390
2024-03-01    390
Name: practice, dtype: int64

In [79]:
data = pd.read_csv("../output/practice_level_data.csv")
data.head(3)

,practice,stp,region,interval_start,appointments_total,pf_impetigo,pf_insectbite,pf_otitismedia,pf_shingles,pf_sinusitis,pf_sorethroat,pf_uti,population,pf_total
0,681,E54000002,London,2024-02-01,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,566,E54000027,North East,2024-02-01,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,196,E54000040,South West,2024-02-01,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [80]:
data['pf_total'].sum()

3.0

In [69]:
data['practice'].nunique()

390

In [76]:
data.groupby('interval_start')['population'].sum()

interval_start
2024-02-01    388.0
2024-03-01    388.0
Name: population, dtype: float64

In [70]:
data.groupby('interval_start')['pf_uti'].sum()

interval_start
2024-02-01    0.0
2024-03-01    0.0
Name: pf_uti, dtype: float64

In [71]:
data.groupby('interval_start')['pf_sorethroat'].sum()

interval_start
2024-02-01    3.0
2024-03-01    0.0
Name: pf_sorethroat, dtype: float64

In [72]:
data.groupby('interval_start')['practice'].nunique()

interval_start
2024-02-01    390
2024-03-01    390
Name: practice, dtype: int64

In [73]:
data['pf_uti'].sum()

0.0

In [74]:
data['pf_sorethroat'].sum()

3.0

In [75]:
data.groupby('interval_start')['pf_sorethroat'].sum()

interval_start
2024-02-01    3.0
2024-03-01    0.0
Name: pf_sorethroat, dtype: float64