In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../output/dataset_patients_2024-02-01.csv.gz")
df.head(10)

,patient_id,start_date,index_date,registered_start,registered_index,alive,sex,age,imd,ethnicity,...,recurrent_uti_12m,recurrent_uti,include_patient_otitis_media,include_patient_sinusitis,include_patient_sore_throat,include_patient_insect_bites,include_patient_shingles,include_patient_impetigo,include_patient_uuti,include_patient_overall_eligible
0,1,2024-02-01,2024-03-01,T,T,T,unknown,91,Missing,Other White,...,F,F,F,T,T,T,T,T,F,T
1,2,2024-02-01,2024-03-01,T,T,T,female,95,Missing,Other White,...,F,F,F,T,T,T,T,T,F,T
2,3,2024-02-01,2024-03-01,T,T,T,male,62,Missing,Other White,...,F,F,F,T,T,T,T,T,F,T
3,4,2024-02-01,2024-03-01,T,T,T,unknown,108,Missing,All other ethnic groups,...,F,F,F,T,T,T,T,T,F,T
4,5,2024-02-01,2024-03-01,T,T,T,male,7,4,All other ethnic groups,...,F,F,T,F,T,T,F,T,F,T
5,6,2024-02-01,2024-03-01,T,T,T,male,89,Missing,Missing,...,F,F,F,T,T,T,T,T,F,T
6,7,2024-02-01,2024-03-01,T,T,T,male,44,5 (Least Deprived),White and Caribbean,...,F,F,F,T,T,T,T,T,F,T
7,8,2024-02-01,2024-03-01,T,T,T,male,99,Missing,Missing,...,F,F,F,T,T,T,T,T,F,T
8,9,2024-02-01,2024-03-01,T,T,T,female,58,3,Bangladeshi,...,F,F,F,T,T,T,T,T,T,T
9,10,2024-02-01,2024-03-01,T,T,T,male,61,Missing,African,...,F,F,F,T,T,T,T,T,F,T

In [4]:
df2 = pd.read_csv("../output/dataset_patients_2024-03-01.csv.gz")
df2.head(10)

,patient_id,start_date,index_date,registered_start,registered_index,alive,sex,age,imd,ethnicity,...,recurrent_uti_12m,recurrent_uti,include_patient_otitis_media,include_patient_sinusitis,include_patient_sore_throat,include_patient_insect_bites,include_patient_shingles,include_patient_impetigo,include_patient_uuti,include_patient_overall_eligible
0,1,2024-03-01,2024-04-01,T,T,T,unknown,91,Missing,Other White,...,F,F,F,T,T,T,T,T,F,T
1,2,2024-03-01,2024-04-01,T,T,T,female,95,Missing,Other White,...,F,F,F,T,T,T,T,T,F,T
2,3,2024-03-01,2024-04-01,T,T,T,male,61,Missing,Other White,...,F,F,F,T,T,T,T,T,F,T
3,4,2024-03-01,2024-04-01,T,T,T,unknown,108,Missing,All other ethnic groups,...,F,F,F,T,T,T,T,T,F,T
4,5,2024-03-01,2024-04-01,T,T,T,male,6,4,All other ethnic groups,...,F,F,T,F,T,T,F,T,F,T
5,6,2024-03-01,2024-04-01,T,T,T,male,88,Missing,Missing,...,F,F,F,T,T,T,T,T,F,T
6,7,2024-03-01,2024-04-01,T,T,T,male,44,5 (Least Deprived),White and Caribbean,...,F,F,F,T,T,T,T,T,F,T
7,8,2024-03-01,2024-04-01,T,T,T,male,100,Missing,Missing,...,F,F,F,T,T,T,T,T,F,T
8,9,2024-03-01,2024-04-01,T,T,T,female,61,Missing,Bangladeshi,...,F,F,F,T,T,T,T,T,T,T
9,10,2024-03-01,2024-04-01,T,T,T,male,60,Missing,African,...,F,F,F,T,T,T,T,T,F,T

Question: why patient_id 9 - age 58 -> 61?